### ISSUE TITLE
[Feature]:  Suggestion

### ISSUE THREAD

**Issue by baraakhateeb** [ruelluna/canvas-pointer#3]
### What happened?

its not a bug, but suggestion to make text inputs for points on image, thanks in advance

### How to reproduce the bug

GG

### Package Version

0

### PHP Version

0

### Laravel Version

0

**Comment by ruelluna** [comment]
Hi there! Text Inputs are complicated to implement as it will hold multiple states. However, I can review an implementation if someone makes a PR.
